postgis:
  image: geographica/postgis:latest
  ports:
    - "5432:5432"
  environment:
    - CREATE_USER=test;test

app:
  build: ./app
  command: nodemon app.js
  dockerfile: Dockerfile
  ports:
    - "17000:17000"
  restart: unless-stopped
  volumes:
    - ./app:/opt/app
  links:
      - postgis
  environment:
  - PGHOST=postgis
  - PGPORT=5432
  - PGUSER=test
  - PGPASS=test
  - ENVIRON=test
  - PORT=17000
  - DEBUG=info,warn,error
